import type { Config, Output } from '@/types'

import { defaultConfig } from '@/lib/config'
import { makeContext } from '@/lib/context'
import { PostgresMetaWithChecks } from '@/lib/meta'
import { transformColumn } from '@/lib/transform'
import { appHooks } from '@/lib/hooks'

import { dirname, resolve } from 'node:path'
import { mkdir, rm, writeFile } from 'node:fs/promises'

export async function generateOutputs(config: Config = defaultConfig) {
    const meta = new PostgresMetaWithChecks({ connectionString: config.url })

    const context = await makeContext(meta, config)

    const outputs: Output[] = []

    for (const configuredOutput of config.outputs) {
        let content = '// This file is generated by supautils\n\n'

        if (configuredOutput.imports) {
            content += configuredOutput.imports.join('\n') + '\n'
        }

        for (const table of context.tables) {
            const columns = table.columns.map((column) => {
                return transformColumn({
                    column,
                    transformers: configuredOutput.transformers,
                })
            })

            const result = configuredOutput.transformers['transform:table']({
                table,
                columns: columns.join(',\n'),
            })

            content += result + '\n\n'
        }

        outputs.push({
            path: resolve(config.outputDir, configuredOutput.path),
            clear: configuredOutput.clear,
            content,
        })
    }

    await meta.end()

    return outputs
}

export async function writeOutputs(outputs: Output[]) {
    for (const output of outputs) {
        await appHooks.callHook('write:before', output)

        const outPath = resolve(process.cwd(), output.path)

        if (output.clear) {
            await rm(outPath)
        }

        mkdir(dirname(outPath), { recursive: true })
        writeFile(outPath, output.content, 'utf8')

        await appHooks.callHook('write:after', output)
    }
}
