import type { Config, Output } from '@/types'

import { defaultConfig } from '@/lib/config'
import { makeContext, transformColumn } from '@/lib/codegen'
import { PostgresMetaWithChecks } from '@/lib/db'
import { appHooks } from '@/lib/hooks'

import { dirname, resolve } from 'node:path'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import defu from 'defu'
import { existsSync } from 'node:fs'

export async function generateOutputs(config: Partial<Config> = defaultConfig) {
    const mergedConfig = defu(config, defaultConfig)
    const meta = new PostgresMetaWithChecks({ connectionString: mergedConfig.url })

    const context = await makeContext(meta, mergedConfig)

    const outputs: Output[] = []

    for (const configuredOutput of context.config.outputs) {
        let content = '// This file is generated by supautils\n\n'

        if (configuredOutput.imports) {
            content += configuredOutput.imports.join('\n') + '\n'
        }

        for (const table of context.tables) {
            const columns = table.columns.map((column) => {
                return transformColumn({
                    column,
                    transformers: configuredOutput.transformers,
                })
            })

            const result = configuredOutput.transformers['transform:table']({
                table,
                columns: columns.join(',\n'),
            })

            content += result + '\n\n'
        }

        outputs.push({
            path: resolve(context.config.outputDir, configuredOutput.path),
            clear: configuredOutput.clear,
            content,
        })
    }

    await meta.end()

    return outputs
}

export async function writeOutputs(outputs: Output[]) {
    for (const output of outputs) {
        await appHooks.callHook('write:before', output)

        const outPath = resolve(process.cwd(), output.path)

        if (output.clear && existsSync(outPath)) {
            await rm(outPath)
        }

        mkdir(dirname(outPath), { recursive: true })
        writeFile(outPath, output.content, 'utf8')

        await appHooks.callHook('write:after', output)
    }
}
