// Generated by supautils on 2025-09-15T14:19:50.319Z
// NOTE: This is a scaffold. Replace with real zod generation logic.
// Detected tables: public.addresses, public.comments, public.companies, public.company_preferences, public.company_skills, public.company_staff, public.legal_forms, public.offer_comments, public.offers, public.profiles, public.project_matches, public.project_preferences, public.project_skills, public.project_tags, public.projects, public.skills, public.tags

import { z } from 'zod'

// TODO: Build Zod schemas based on postgres-meta introspection
export const tables = [
  "public.addresses",
  "public.comments",
  "public.companies",
  "public.company_preferences",
  "public.company_skills",
  "public.company_staff",
  "public.legal_forms",
  "public.offer_comments",
  "public.offers",
  "public.profiles",
  "public.project_matches",
  "public.project_preferences",
  "public.project_skills",
  "public.project_tags",
  "public.projects",
  "public.skills",
  "public.tags"
] as const

